### ISSUE TITLE
Installation directions

### ISSUE THREAD

**Issue by czaplicki** [OmarCastro/cmd-polkit#1]
Hey, from what a gathered from reading your code in the example directory.
This is exactly what I've been looking for, just one a problem, how does one build and install it?
The example references build directory, but it's not include in the repository (excluded by .gitignore)
A README.md file describing how to build and install would be great!
and maybe a quick overview on what messages you receive and what to respond  with,
when writing a script like the python example.

**Comment by OmarCastro** [comment]
Hello @czaplicki, I added a README with the installation instructions, as well as the dependencies used for this project, honestly, I do not remember why I did opt out the README.

I will fill it with usage instructions later.

**Comment by czaplicki** [comment]
Tack you! after a bit of fiddling I manged to write my own implementation using rofi ^^
If your interested I just published it as a gist
https://gist.github.com/czaplicki/205ebc6292cc800df6c4f3327fe0e749
